language: node_js
node_js:
- stable
env:
  global:
  - VERSION=1.2
before_script:
- phantomjs -v
before_deploy:
- zip -r bluefin.zip src/*
- sed -i -e "s/{{version}}/${VERSION}/" .bintray.json
- sed -i -e "s/{{patch}}/${TRAVIS_BUILD_NUMBER}/" .bintray.json
- sed -i -e "s/{{branch}}/${TRAVIS_BRANCH}/" .bintray.json
- build_date=`date +%Y-%m-%d`
- sed -i -e "s/{{releasedate}}/${build_date}/" .bintray.json

deploy:
  provider: releases
  api_key:
    secure: QWoOT9ajir6YyImu4HkCo8y9QdqnU+yX+a7uB5Cxrf4XhlE1nSisayWRy29it7T4w0a2E208IZKS+YOXA7N8BjUnEmziKrutz9GxVQmoVmlQbDpgkTn6ga9NhgMvDOHYaSLohylNL7OSqNLlorThXYXLlXCOsydpwkkI0JE+PyA=
  file: bluefin.zip
  on:
    repo: davidroberts63/OctoPygmy
